### ISSUE TITLE
Hi, pls help me,TKS

### ISSUE THREAD

**Issue by lichao3140** [ClouddJR/Petty-Pets-Care-Health#2]
04-30 12:17:52.622 17605-17605/com.clouddroid.petscarehealth E/CredentialSignInHandler: Unexpected exception when signing in with credential google.com unsuccessful. Visit https://console.firebase.google.com to enable it.
    com.google.firebase.auth.i: This operation is not allowed. You must enable this service in the console.
        at com.google.android.gms.internal.acf.a(Unknown Source)
        at com.google.android.gms.internal.abv.a(Unknown Source)
        at com.google.android.gms.internal.acq.a(Unknown Source)
        at com.google.android.gms.internal.acs.a(Unknown Source)
        at com.google.android.gms.internal.ach.onTransact(Unknown Source)
        at android.os.Binder.execTransact(Binder.java:455)

**Comment by ClouddJR** [comment]
Don't use Google Sign-In option, just login with email/password
